### ISSUE TITLE
PacVis distribution not found

### ISSUE THREAD

**Issue by Chilzi** [farseerfc/pacvis#6]
With the current version (0.2.7.r4.g30b2956-1) from the AUR the bin won't run.
The error message is 
`pkg_resources.DistributionNotFound: The 'PacVis==0.2.7' distribution was not found and is required by the application`
this might be due to the python 3.8 update not so long ago?

Reinstalling didn't help. Installed the package via pikaur from the AUR with no error messages, I'm on arch 5.4.3.
Thanks.

**Comment by farseerfc** [comment]
You need to rebuild your packages from AUR by yourself. pikaur may cache the built package so you will need to let it rebuild instead of only reinstalling the package. Try clean pikaur package cache and rebuild it.
Or there is already built package in [archlinuxcn], I am maintaining the package myself there:
https://github.com/archlinuxcn/repo/blob/master/README.md
